service: aws-csharp # NOTE: update this with your service name

provider:
  name: aws
  runtime: dotnetcore2.1
  region: eu-west-2

package:
  artifact: bin/release/netcoreapp2.1/deploy-package.zip

functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
