apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: mssql-deployment

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: microsoft/mssql-server-linux
        name: sql-server                              
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
        - name: mssql-persistent-storage
          persistentVolumeClaim:
            claimName: mssql-data-claim
  